"""Simple local Milvus demo using POEM's real embeddings.

Self-contained so it can be run against a local Milvus Standalone container
started with:

    docker compose -f embeddings/docker/milvus-compose.yml up -d

It demonstrates, using the real qwen3-embedding vectors generated by
Pipeline/generate_embeddings.py (not random placeholder data):
- connecting to a local Milvus server
- creating a fresh collection every run (dim derived from the loaded vectors)
- loading a handful of real .npy embeddings + their source text
- inserting them and running a cosine similarity search
- printing exactly what was loaded, created, and found
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from typing import Any

import numpy as np

try:
    from pymilvus import DataType, MilvusClient
except ImportError as exc:  # pragma: no cover - import-time guard
    raise SystemExit(
        "pymilvus is required. Install it with `pip install pymilvus` or `pip install -e embeddings[milvus]`."
    ) from exc

_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(_HERE))          # embeddings/ root -> import poem_core
from poem_core.docker_preflight import ensure_milvus_ready, is_local_uri

_EMBEDDINGS_DIR = os.path.join(os.path.dirname(_HERE), "Pipeline")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run a simple local Milvus demo over real POEM embeddings")
    parser.add_argument("--uri", default=os.environ.get("MILVUS_URI", "http://localhost:19530"), help="Milvus endpoint")
    parser.add_argument("--token", default=os.environ.get("MILVUS_TOKEN", ""), help="Milvus token if required")
    parser.add_argument("--collection", default=os.environ.get("MILVUS_COLLECTION", "poem_npy_demo"), help="Collection name")
    parser.add_argument("--section", default="instruments", choices=["instruments", "scales", "collections"],
                         help="Which Pipeline/<section> folder to sample real embeddings from")
    parser.add_argument("--n", type=int, default=5, help="How many .npy embeddings to load")
    return parser.parse_args()


def make_client(uri: str, token: str) -> MilvusClient:
    return MilvusClient(uri=uri, token=token) if token else MilvusClient(uri=uri)


def load_sample_rows(section: str, n: int) -> list[dict[str, Any]]:
    """Load the first N real embeddings for a corpus section (manifest-ordered).

    Mirrors the manifest-preferred path in poem_core/corpus.py's
    load_embeddings, capped to n files instead of the full ~778-vector corpus,
    so this demo only ever touches n .npy files on disk.
    """
    section_dir = os.path.join(_EMBEDDINGS_DIR, section)
    with open(os.path.join(section_dir, "manifest.json"), encoding="utf-8") as f:
        manifest = json.load(f)[:n]
    texts = np.load(os.path.join(section_dir, "texts.npy"), allow_pickle=True)

    rows = []
    for i, entry in enumerate(manifest):
        vector = np.load(os.path.join(section_dir, entry["file"])).astype(np.float32)
        rows.append(
            {
                "id": i,
                "vector": vector,
                "text": str(texts[i]),
                "file": entry["file"],
                "section": section,
            }
        )
    return rows


def create_collection(client: MilvusClient, collection_name: str, dim: int) -> None:
    if client.has_collection(collection_name):
        client.drop_collection(collection_name)

    schema = client.create_schema(auto_id=False, enable_dynamic_field=True)
    schema.add_field("id", DataType.INT64, is_primary=True)
    schema.add_field("vector", DataType.FLOAT_VECTOR, dim=dim)
    schema.add_field("text", DataType.VARCHAR, max_length=2000)
    schema.add_field("file", DataType.VARCHAR, max_length=200)
    schema.add_field("section", DataType.VARCHAR, max_length=50)

    index_params = client.prepare_index_params()
    index_params.add_index(field_name="vector", index_type="FLAT", metric_type="COSINE")
    client.create_collection(collection_name=collection_name, schema=schema, index_params=index_params)


def preview(text: str, width: int = 70) -> str:
    text = text.replace("\n", " ").strip()
    return text if len(text) <= width else text[: width - 1] + "..."


def run_demo(uri: str, token: str, collection_name: str, section: str, n: int) -> None:
    if is_local_uri(uri):
        ensure_milvus_ready()
    client = make_client(uri, token)

    try:
        client.list_collections()
    except Exception as exc:  # pragma: no cover - depends on local Docker availability
        raise SystemExit(f"Unable to reach Milvus at {uri}: {exc}\nStart it with: docker compose -f embeddings/docker/milvus-compose.yml up -d") from exc

    rows = load_sample_rows(section, n)
    dim = len(rows[0]["vector"])

    print(f"Loaded {len(rows)} real embeddings from Pipeline/{section}/ (qwen3-embedding, {dim}-dim,")
    print("generated by Pipeline/generate_embeddings.py -- not random placeholder data):")
    for row in rows:
        print(f"  [{row['id']}] {row['file']:35s} {preview(row['text'])}")

    create_collection(client, collection_name, dim)
    print(f"\nFresh collection '{collection_name}' created (dropped any prior instance):")
    print(f"  fields: id(INT64,pk) | vector(FLOAT_VECTOR,dim={dim}) | text(VARCHAR) | file(VARCHAR) | section(VARCHAR)")
    print("  index: FLAT / metric_type=COSINE")

    insert_rows = [{"id": r["id"], "vector": r["vector"].tolist(), "text": r["text"], "file": r["file"], "section": r["section"]} for r in rows]
    client.insert(collection_name, insert_rows)
    client.load_collection(collection_name)
    print(f"\nInserted {len(rows)} rows and loaded the collection into memory.")

    query_row = rows[0]
    search_results = client.search(
        collection_name=collection_name,
        data=[query_row["vector"].tolist()],
        limit=len(rows),
        output_fields=["text", "file", "section"],
        search_params={"metric_type": "COSINE"},
        # "Strong" forces this search to see the rows just inserted/loaded above,
        # instead of Milvus's default bounded-staleness read.
        consistency_level="Strong",
    )

    print(f"\nCosine similarity search (query = row 0: {query_row['file']}):")
    for rank, hit in enumerate(search_results[0], start=1):
        entity = hit.get("entity", {})
        print(f"  rank {rank}  score={hit['distance']:.4f}  file={entity.get('file'):35s} {preview(entity.get('text', ''))}")

    print(
        "\nThese vectors are the same qwen3-embedding vectors your pipeline generates "
        "(see poem_core/embedding_client.py + Pipeline/generate_embeddings.py) -- not random data."
    )
    print(
        "To search the full corpus instead of this 5-file sample, see "
        "Pipeline/search_similarity.py, docker/milvus_admin.py (push), and docker/check_milvus.py (verify)."
    )


if __name__ == "__main__":
    args = parse_args()
    run_demo(args.uri, args.token, args.collection, args.section, args.n)
