services:
  browser-backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile-browser-backend
    image: poem-browser-backend:latest
    container_name: poem-browser-backend
    expose:
    - "8000"
    networks:
      - browser-net

  browser-frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile-browser-frontend
    image: poem-browser-frontend:latest
    container_name: poem-browser-frontend
    depends_on:
      - browser-backend
    ports:
      - "8080:80"
    networks:
      - browser-net

networks:
  browser-net:
    driver: bridge
