FROM sbtscala/scala-sbt:eclipse-temurin-21.0.6_7_1.10.10_3.3.5 AS build-java

RUN apt-get update && apt-get install -y unzip
ENV JAVA_OPTS="-Xms6048m -Xmx10000m"

COPY ./poem-demo /poem-demo

WORKDIR /poem-demo

RUN sbt clean
RUN sbt playUpdateSecret && sbt dist

RUN cd /poem-demo/target/universal/ && unzip poem-demo-1.0-SNAPSHOT.zip

FROM eclipse-temurin:21-jre

COPY --from=build-java /poem-demo/target/universal/poem-demo-1.0-SNAPSHOT /poem-demo

EXPOSE 9000

ENTRYPOINT [ "bin/poem-demo" ]