FROM hansidm/fuseki:latest

COPY /poem-demo/dist/data /data
COPY /ontology /data
COPY POEM.rdf /data
RUN tdb2.tdbloader --loc=/ds/tdb2 /data/*.ttl
RUN tdb2.tdbloader --loc=/ds/tdb2 /data/*.rdf
RUN tdb2.tdbloader --loc=/ds/tdb2 /data/*.owl
RUN rm -rf /data
 
WORKDIR /usr/local/fuseki
RUN java -cp fuseki-server.jar jena.textindexer --desc=/usr/local/fuseki/run/config.ttl