FROM sbtscala/scala-sbt:eclipse-temurin-21.0.6_7_1.10.10_3.3.5 as build-java

RUN apt-get update && apt-get install -y unzip
ENV JAVA_OPTS="-Xms6048m -Xmx10000m"

WORKDIR /poem-demo

COPY ./poem-demo /poem-demo

RUN sbt clean
RUN sbt playUpdateSecret && sbt dist

RUN cd /poem-demo/target/universal/ && unzip poem-demo-1.0-SNAPSHOT.zip

WORKDIR /poem-demo

COPY --from=build-java /poem-demo/target/universal/hascoapi-1.0-SNAPSHOT /poem-demo

EXPOSE 9000

ENTRYPOINT [ "bin/poem-demo" ]