FROM node:lts-alpine AS build

WORKDIR /frontend
COPY ./browser/frontend/package*.json .
RUN npm ci

COPY ./browser/frontend/. .
RUN npm run build

FROM nginx:alpine

COPY --from=build /frontend/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]