FROM sbtscala/scala-sbt:eclipse-temurin-21.0.7_6_1.11.0_3.3.6 AS build-java

RUN apt-get update && apt-get install -y unzip curl
RUN curl -fsSL https://deb.nodesource.com/setup_22.x -o nodesource_setup.sh
RUN bash nodesource_setup.sh
RUN apt-get install -y nodejs
ENV JAVA_OPTS="-Xms6048m -Xmx10000m"

COPY ./poem-demo /poem-demo

WORKDIR /poem-demo

RUN sbt clean
RUN sbt playUpdateSecret && sbt dist

RUN cd /poem-demo/target/universal/ && unzip poem-demo-1.0-SNAPSHOT.zip

FROM eclipse-temurin:21-jre

COPY --from=build-java /poem-demo/target/universal/poem-demo-1.0-SNAPSHOT /poem-demo

WORKDIR /poem-demo

EXPOSE 9000

ENTRYPOINT [ "bin/poem-demo" ]