FROM node:lts-alpine AS build

WORKDIR /frontend

COPY browser/frontend/package*.json .
RUN npm ci

COPY browser/frontend/. .
RUN npm run build


FROM nginx:alpine

COPY --from=build /frontend/dist /usr/share/nginx/html


RUN printf "server { \
    listen 80; \
    server_name localhost; \
    root /usr/share/nginx/html; \
    index index.html; \
    location / { try_files \$uri /index.html; } \
}" > /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]